package com.v2ray.ang.util

import android.content.Context
import com.v2ray.ang.R
import java.text.Normalizer
import java.util.Locale
import java.util.regex.Pattern

object CountryUtils {

    fun getFlagResId(context: Context, remark: String?): Int {
        if (remark.isNullOrEmpty()) return R.drawable.unknown

        // اولویت ۱: استیکر و ایموجی پرچم موجود در ریمارک کانفیگ
        val emojiCode = extractCountryCodeFromEmoji(remark)
        if (emojiCode != null) {
            val resId = getResId(context, emojiCode)
            if (resId != 0) return resId
        }

        // نرمال‌سازی متن (تبدیل فونت‌های خاص و کوچک‌سازی کاراکترها)
        val normalizedRemark = normalizeText(remark)

        // اولویت ۲: جستجوی نام کامل کشور و شهرهای اصلی به انگلیسی
        var code = detectByFullName(normalizedRemark)

        // اولویت ۳: در صورت عدم تطابق با نام کامل، بررسی حروف دو حرفی و اسامی فارسی
        if (code == null) {
            code = detectByShortCodeOrPersian(normalizedRemark)
        }

        val finalCode = code ?: "unknown"
        val resId = getResId(context, finalCode)
        if (resId == 0) {
            val unknownId = context.resources.getIdentifier("unknown", "drawable", context.packageName)
            return if (unknownId != 0) unknownId else R.drawable.unknown
        }
        return resId
    }

    private fun getResId(context: Context, code: String): Int {
        var resId = context.resources.getIdentifier(code, "drawable", context.packageName)
        if (resId == 0) {
            resId = context.resources.getIdentifier("flag_$code", "drawable", context.packageName)
        }
        return resId
    }

    /**
     * استخراج کد دو حرفی بر اساس ایموجی پرچم (مثل 🇩🇪 -> "de")
     */
    private fun extractCountryCodeFromEmoji(text: String): String? {
        val flagPattern = Pattern.compile("[\\uD83C][\\uDDE6-\\uDDFF][\\uD83C][\\uDDE6-\\uDDFF]")
        val matcher = flagPattern.matcher(text)
        if (matcher.find()) {
            val flag = matcher.group()
            val sb = StringBuilder()
            var i = 0
            while (i < flag.length) {
                val codePoint = flag.codePointAt(i)
                if (codePoint in 0x1F1E6..0x1F1FF) {
                    sb.append((codePoint - 0x1F1E6 + 'a'.code).toChar())
                }
                i += Character.charCount(codePoint)
            }
            if (sb.length == 2) return sb.toString()
        }
        return null
    }

    private fun normalizeText(text: String): String {
        var normalized = Normalizer.normalize(text, Normalizer.Form.NFKC)
        normalized = normalized.lowercase(Locale.ROOT)
        return normalized
    }

    /**
     * اولویت دوم: تطابق بر اساس نام کامل انگلیسی و شهرهای معروف
     */
    private fun detectByFullName(text: String): String? {
        return when {
            containsExact(text, "andorra") -> "ad"
            containsExact(text, "united arab emirates", "emirates", "dubai", "abudhabi") -> "ae"
            containsExact(text, "afghanistan") -> "af"
            containsExact(text, "antigua", "barbuda") -> "ag"
            containsExact(text, "anguilla") -> "ai"
            containsExact(text, "albania") -> "al"
            containsExact(text, "armenia") -> "am"
            containsExact(text, "angola") -> "ao"
            containsExact(text, "antarctica") -> "aq"
            containsExact(text, "argentina") -> "ar"
            containsExact(text, "american samoa") -> "as"
            containsExact(text, "austria", "vienna") -> "at"
            containsExact(text, "australia", "sydney", "melbourne") -> "au"
            containsExact(text, "aruba") -> "aw"
            containsExact(text, "aland") -> "ax"
            containsExact(text, "azerbaijan", "baku") -> "az"
            containsExact(text, "bosnia", "herzegovina") -> "ba"
            containsExact(text, "barbados") -> "bb"
            containsExact(text, "bangladesh") -> "bd"
            containsExact(text, "belgium", "brussels") -> "be"
            containsExact(text, "burkina faso") -> "bf"
            containsExact(text, "bulgaria", "sofia") -> "bg"
            containsExact(text, "bahrain") -> "bh"
            containsExact(text, "burundi") -> "bi"
            containsExact(text, "benin") -> "bj"
            containsExact(text, "st barthelemy") -> "bl"
            containsExact(text, "bermuda") -> "bm"
            containsExact(text, "brunei") -> "bn"
            containsExact(text, "bolivia") -> "bo"
            containsExact(text, "bonaire") -> "bq"
            containsExact(text, "brazil", "sao paulo") -> "br"
            containsExact(text, "bahamas") -> "bs"
            containsExact(text, "bhutan") -> "bt"
            containsExact(text, "bouvet") -> "bv"
            containsExact(text, "botswana") -> "bw"
            containsExact(text, "belarus", "minsk") -> "by"
            containsExact(text, "belize") -> "bz"
            containsExact(text, "canada", "montreal", "vancouver", "toronto") -> "ca"
            containsExact(text, "cocos") -> "cc"
            containsExact(text, "congo") -> "cd"
            containsExact(text, "central african") -> "cf"
            containsExact(text, "congo brazzaville") -> "cg"
            containsExact(text, "switzerland", "zurich", "geneva") -> "ch"
            containsExact(text, "ivory coast", "cote d'ivoire") -> "ci"
            containsExact(text, "cook islands") -> "ck"
            containsExact(text, "chile", "santiago") -> "cl"
            containsExact(text, "cameroon") -> "cm"
            containsExact(text, "china", "beijing", "shanghai", "shenzhen") -> "cn"
            containsExact(text, "colombia", "bogota") -> "co"
            containsExact(text, "costa rica") -> "cr"
            containsExact(text, "cuba") -> "cu"
            containsExact(text, "cape verde") -> "cv"
            containsExact(text, "curacao") -> "cw"
            containsExact(text, "christmas island") -> "cx"
            containsExact(text, "cyprus", "nicosia") -> "cy"
            containsExact(text, "czech", "czech republic", "prague") -> "cz"
            containsExact(text, "germany", "deutschland", "frankfurt", "falkenstein", "berlin", "hetzner") -> "de"
            containsExact(text, "djibouti") -> "dj"
            containsExact(text, "denmark", "copenhagen") -> "dk"
            containsExact(text, "dominica") -> "dm"
            containsExact(text, "dominican republic") -> "dom"
            containsExact(text, "algeria") -> "dz"
            containsExact(text, "ecuador") -> "ec"
            containsExact(text, "estonia", "tallinn") -> "ee"
            containsExact(text, "egypt", "cairo") -> "eg"
            containsExact(text, "western sahara") -> "eh"
            containsExact(text, "eritrea") -> "er"
            containsExact(text, "spain", "madrid", "barcelona") -> "es"
            containsExact(text, "ethiopia") -> "et"
            containsExact(text, "finland", "helsinki") -> "fi"
            containsExact(text, "fiji") -> "fj"
            containsExact(text, "falkland") -> "fk"
            containsExact(text, "micronesia") -> "fm"
            containsExact(text, "faroe") -> "fo"
            containsExact(text, "france", "paris", "marseille") -> "fr"
            containsExact(text, "gabon") -> "ga"
            containsExact(text, "england") -> "gb_eng"
            containsExact(text, "northern ireland") -> "gb_nir"
            containsExact(text, "scotland") -> "gb_sct"
            containsExact(text, "wales") -> "gb_wls"
            containsExact(text, "united kingdom", "britain", "london", "manchester") -> "gb"
            containsExact(text, "grenada") -> "gd"
            containsExact(text, "georgia", "tbilisi") -> "ge"
            containsExact(text, "french guiana") -> "gf"
            containsExact(text, "guernsey") -> "gg"
            containsExact(text, "ghana") -> "gh"
            containsExact(text, "gibraltar") -> "gi"
            containsExact(text, "greenland") -> "gl"
            containsExact(text, "gambia") -> "gm"
            containsExact(text, "guinea") -> "gn"
            containsExact(text, "guadeloupe") -> "gp"
            containsExact(text, "equatorial guinea") -> "gq"
            containsExact(text, "greece", "athens") -> "gr"
            containsExact(text, "south georgia") -> "gs"
            containsExact(text, "guatemala") -> "gt"
            containsExact(text, "guam") -> "gu"
            containsExact(text, "guinea-bissau") -> "gw"
            containsExact(text, "guyana") -> "gy"
            containsExact(text, "hong kong") -> "hk"
            containsExact(text, "heard island") -> "hm"
            containsExact(text, "honduras") -> "hn"
            containsExact(text, "croatia", "zagreb") -> "hr"
            containsExact(text, "haiti") -> "ht"
            containsExact(text, "hungary", "budapest") -> "hu"
            containsExact(text, "indonesia", "jakarta") -> "id"
            containsExact(text, "ireland", "dublin") -> "ie"
            containsExact(text, "israel", "tel aviv") -> "il"
            containsExact(text, "isle of man") -> "im"
            containsExact(text, "india", "mumbai", "delhi", "bangalore") -> "ind"
            containsExact(text, "british indian ocean") -> "io"
            containsExact(text, "iraq", "baghdad") -> "iq"
            containsExact(text, "iran", "tehran", "shiraz", "mashhad", "isfahan", "tabriz", "irancell", "mci", "shatel") -> "ir"
            containsExact(text, "iceland", "reykjavik") -> "is"
            containsExact(text, "italy", "rome", "milan") -> "it"
            containsExact(text, "jersey") -> "je"
            containsExact(text, "jamaica") -> "jm"
            containsExact(text, "jordan", "amman") -> "jo"
            containsExact(text, "japan", "tokyo", "osaka") -> "jp"
            containsExact(text, "kenya", "nairobi") -> "ke"
            containsExact(text, "kyrgyzstan") -> "kg"
            containsExact(text, "cambodia") -> "kh"
            containsExact(text, "kiribati") -> "ki"
            containsExact(text, "comoros") -> "km"
            containsExact(text, "st kitts") -> "kn"
            containsExact(text, "north korea", "pyongyang") -> "kp"
            containsExact(text, "south korea", "seoul") -> "kr"
            containsExact(text, "kuwait") -> "kw"
            containsExact(text, "cayman islands") -> "ky"
            containsExact(text, "kazakhstan", "almaty", "astana") -> "kz"
            containsExact(text, "laos") -> "la"
            containsExact(text, "lebanon", "beirut") -> "lb"
            containsExact(text, "st lucia") -> "lc"
            containsExact(text, "liechtenstein") -> "li"
            containsExact(text, "sri lanka") -> "lk"
            containsExact(text, "liberia") -> "lr"
            containsExact(text, "lesotho") -> "ls"
            containsExact(text, "lithuania", "vilnius") -> "lt"
            containsExact(text, "luxembourg") -> "lu"
            containsExact(text, "latvia", "riga") -> "lv"
            containsExact(text, "libya", "tripoli") -> "ly"
            containsExact(text, "morocco", "casablanca") -> "ma"
            containsExact(text, "monaco") -> "mc"
            containsExact(text, "moldova") -> "md"
            containsExact(text, "montenegro") -> "me"
            containsExact(text, "st martin") -> "mf"
            containsExact(text, "madagascar") -> "mg"
            containsExact(text, "marshall islands") -> "mh"
            containsExact(text, "macedonia", "skopje") -> "mk"
            containsExact(text, "mali") -> "ml"
            containsExact(text, "myanmar", "burma") -> "mm"
            containsExact(text, "mongolia") -> "mn"
            containsExact(text, "macau") -> "mo"
            containsExact(text, "northern mariana") -> "mp"
            containsExact(text, "martinique") -> "mq"
            containsExact(text, "mauritania") -> "mr"
            containsExact(text, "montserrat") -> "ms"
            containsExact(text, "malta") -> "mt"
            containsExact(text, "mauritius") -> "mu"
            containsExact(text, "maldives") -> "mv"
            containsExact(text, "malawi") -> "mw"
            containsExact(text, "mexico") -> "mx"
            containsExact(text, "malaysia", "kuala lumpur") -> "my"
            containsExact(text, "mozambique") -> "mz"
            containsExact(text, "namibia") -> "na"
            containsExact(text, "new caledonia") -> "nc"
            containsExact(text, "niger") -> "ne"
            containsExact(text, "norfolk island") -> "nf"
            containsExact(text, "nigeria", "lagos") -> "ng"
            containsExact(text, "nicaragua") -> "ni"
            containsExact(text, "netherlands", "amsterdam", "holland") -> "nl"
            containsExact(text, "norway", "oslo") -> "no"
            containsExact(text, "nepal") -> "np"
            containsExact(text, "nauru") -> "nr"
            containsExact(text, "niue") -> "nu"
            containsExact(text, "new zealand", "auckland") -> "nz"
            containsExact(text, "oman", "muscat") -> "om"
            containsExact(text, "panama") -> "pa"
            containsExact(text, "peru", "lima") -> "pe"
            containsExact(text, "french polynesia") -> "pf"
            containsExact(text, "papua new guinea") -> "pg"
            containsExact(text, "philippines", "manila") -> "ph"
            containsExact(text, "pakistan", "karachi") -> "pk"
            containsExact(text, "poland", "warsaw") -> "pl"
            containsExact(text, "st pierre") -> "pm"
            containsExact(text, "pitcairn") -> "pn"
            containsExact(text, "puerto rico") -> "pr"
            containsExact(text, "palestine", "gaza") -> "ps"
            containsExact(text, "portugal", "lisbon") -> "pt"
            containsExact(text, "palau") -> "pw"
            containsExact(text, "paraguay") -> "py"
            containsExact(text, "qatar", "doha") -> "qa"
            containsExact(text, "reunion") -> "re"
            containsExact(text, "romania", "bucharest") -> "ro"
            containsExact(text, "serbia", "belgrade") -> "rs"
            containsExact(text, "russia", "moscow", "saint petersburg") -> "ru"
            containsExact(text, "rwanda") -> "rw"
            containsExact(text, "saudi arabia", "riyadh", "jeddah") -> "sa"
            containsExact(text, "solomon islands") -> "sb"
            containsExact(text, "seychelles") -> "sc"
            containsExact(text, "sudan") -> "sd"
            containsExact(text, "sweden", "stockholm") -> "se"
            containsExact(text, "singapore") -> "sg"
            containsExact(text, "st helena") -> "sh"
            containsExact(text, "slovenia", "ljubljana") -> "si"
            containsExact(text, "svalbard", "jan mayen") -> "sj"
            containsExact(text, "slovakia", "bratislava") -> "sk"
            containsExact(text, "sierra leone") -> "sl"
            containsExact(text, "san marino") -> "sm"
            containsExact(text, "senegal") -> "sn"
            containsExact(text, "somalia") -> "so"
            containsExact(text, "suriname") -> "sr"
            containsExact(text, "south sudan") -> "ss"
            containsExact(text, "sao tome") -> "st"
            containsExact(text, "el salvador") -> "sv"
            containsExact(text, "sint maarten") -> "sx"
            containsExact(text, "syria", "damascus") -> "sy"
            containsExact(text, "eswatini", "swaziland") -> "sz"
            containsExact(text, "turks and caicos") -> "tc"
            containsExact(text, "chad") -> "td"
            containsExact(text, "french southern territories") -> "tf"
            containsExact(text, "togo") -> "tg"
            containsExact(text, "thailand", "bangkok") -> "th"
            containsExact(text, "tajikistan") -> "tj"
            containsExact(text, "tokelau") -> "tk"
            containsExact(text, "timor-leste") -> "tl"
            containsExact(text, "turkmenistan") -> "tm"
            containsExact(text, "tunisia") -> "tn"
            containsExact(text, "tonga") -> "to"
            containsExact(text, "turkey", "ankara", "istanbul") -> "tr"
            containsExact(text, "trinidad", "tobago") -> "tt"
            containsExact(text, "tuvalu") -> "tv"
            containsExact(text, "taiwan", "taipei") -> "tw"
            containsExact(text, "tanzania") -> "tz"
            containsExact(text, "ukraine", "kiev", "kyiv") -> "ua"
            containsExact(text, "uganda") -> "ug"
            containsExact(text, "us minor outlying") -> "um"
            containsExact(text, "united states", "america", "new york", "california", "los angeles", "chicago", "miami") -> "us"
            containsExact(text, "uruguay") -> "uy"
            containsExact(text, "uzbekistan", "tashkent") -> "uz"
            containsExact(text, "vatican", "holy see") -> "va"
            containsExact(text, "st vincent", "grenadines") -> "vc"
            containsExact(text, "venezuela", "caracas") -> "ve"
            containsExact(text, "british virgin islands") -> "vg"
            containsExact(text, "us virgin islands") -> "vi"
            containsExact(text, "vietnam", "hanoi") -> "vn"
            containsExact(text, "vanuatu") -> "vu"
            containsExact(text, "wallis", "futuna") -> "wf"
            containsExact(text, "samoa") -> "ws"
            containsExact(text, "kosovo") -> "xk"
            containsExact(text, "yemen") -> "ye"
            containsExact(text, "mayotte") -> "yt"
            containsExact(text, "south africa", "johannesburg", "cape town") -> "za"
            containsExact(text, "zambia") -> "zm"
            containsExact(text, "zimbabwe") -> "zw"
            else -> null
        }
    }

    /**
     * اولویت سوم: تطابق بر اساس حروف دو حرفی اختصاصی و اسامی فارسی
     */
    private fun detectByShortCodeOrPersian(text: String): String? {
        return when {
            containsMatch(text, "امارات", "دبی", "ابوظبی", "ae", "uae") -> "ae"
            containsMatch(text, "افغانستان", "کابل", "af") -> "af"
            containsMatch(text, "آلبانی", "البانی", "al") -> "al"
            containsMatch(text, "ارمنستان", "ایروان", "am") -> "am"
            containsMatch(text, "آنگولا", "انگو", "ان hisگولا", "ao") -> "ao"
            containsMatch(text, "آرژانتین", "ارژانتین", "ar") -> "ar"
            containsMatch(text, "اتریش", "وین", "at") -> "at"
            containsMatch(text, "استرالیا", "سیدنی", "ملبورن", "au") -> "au"
            containsMatch(text, "آذربایجان", "باکو", "az") -> "az"
            containsMatch(text, "بوسنی", "ba") -> "ba"
            containsMatch(text, "بنگلادش", "bd") -> "bd"
            containsMatch(text, "بلژیک", "بروکسل", "be") -> "be"
            containsMatch(text, "بلغارستان", "صوفیه", "bg") -> "bg"
            containsMatch(text, "بحرین", "bh") -> "bh"
            containsMatch(text, "برونئی", "bn") -> "bn"
            containsMatch(text, "بولیوی", "bo") -> "bo"
            containsMatch(text, "برزیل", "br") -> "br"
            containsMatch(text, "باهاما", "bs") -> "bs"
            containsMatch(text, "بوتان", "bt") -> "bt"
            containsMatch(text, "بلاروس", "by") -> "by"
            containsMatch(text, "بلیز", "bz") -> "bz"
            containsMatch(text, "کانادا", "مونترال", "ونکوور", "تورنتو", "ca") -> "ca"
            containsMatch(text, "کنگو", "cd") -> "cd"
            containsMatch(text, "سوئیس", "زوریخ", "ژنو", "ch") -> "ch"
            containsMatch(text, "شیلی", "cl") -> "cl"
            containsMatch(text, "کامرون", "cm") -> "cm"
            containsMatch(text, "چین", "پکن", "شانگهای", "cn") -> "cn"
            containsMatch(text, "کلمبیا", "co") -> "co"
            containsMatch(text, "کاستاریکا", "cr") -> "cr"
            containsMatch(text, "کوبا", "cu") -> "cu"
            containsMatch(text, "قبرس", "cy") -> "cy"
            containsMatch(text, "چک", "پراگ", "cz") -> "cz"
            containsMatch(text, "آلمان", "المان", "فرانکفورت", "برلین", "هتزنر", "de") -> "de"
            containsMatch(text, "دانمارک", "کپنهاگ", "dk") -> "dk"
            containsMatch(text, "الجزایر", "dz") -> "dz"
            containsMatch(text, "اکوادور", "ec") -> "ec"
            containsMatch(text, "استونی", "تالین", "ee") -> "ee"
            containsMatch(text, "مصر", "قاهره", "eg") -> "eg"
            containsMatch(text, "اریتره", "er") -> "er"
            containsMatch(text, "اسپانیا", "مادرید", "بارسلونا", "es") -> "es"
            containsMatch(text, "اتیوپی", "et") -> "et"
            containsMatch(text, "فنلاند", "هلسینکی", "fi") -> "fi"
            containsMatch(text, "فیجی", "fj") -> "fj"
            containsMatch(text, "فرانسه", "پاریس", "مارسی", "fr") -> "fr"
            containsMatch(text, "گابن", "ga") -> "ga"
            containsMatch(text, "انگلیس", "gb_eng") -> "gb_eng"
            containsMatch(text, "ایرلند شمالی", "gb_nir") -> "gb_nir"
            containsMatch(text, "اسکاتلند", "gb_sct") -> "gb_sct"
            containsMatch(text, "ولز", "gb_wls") -> "gb_wls"
            containsMatch(text, "بریتانیا", "انگلستان", "لندن", "منچستر", "gb", "uk") -> "gb"
            containsMatch(text, "گرجستان", "تفلیس", "ge") -> "ge"
            containsMatch(text, "غنا", "gh") -> "gh"
            containsMatch(text, "جبل الطارق", "gi") -> "gi"
            containsMatch(text, "گرینلند", "gl") -> "gl"
            containsMatch(text, "گامبیا", "gm") -> "gm"
            containsMatch(text, "گینه", "gn") -> "gn"
            containsMatch(text, "یونان", "آتن", "gr") -> "gr"
            containsMatch(text, "گواتمالا", "gt") -> "gt"
            containsMatch(text, "گوآم", "gu") -> "gu"
            containsMatch(text, "هنگ کنگ", "hk") -> "hk"
            containsMatch(text, "هندوراس", "hn") -> "hn"
            containsMatch(text, "کرواسی", "زاگرب", "hr") -> "hr"
            containsMatch(text, "هائیتی", "ht") -> "ht"
            containsMatch(text, "مجارستان", "بوداپست", "hu") -> "hu"
            containsMatch(text, "اندونزی", "جاکارتا", "id") -> "id"
            containsMatch(text, "ایرلند", "دوبلین", "ie") -> "ie"
            containsMatch(text, "اسرائیل", "تلاویو", "il") -> "il"
            containsMatch(text, "هند", "هندوستان", "دهلی", "بمبئی", "مومبای", "in", "ind") -> "ind"
            containsMatch(text, "عراق", "بغداد", "iq") -> "iq"
            containsMatch(text, "ایران", "تهران", "شیراز", "مشهد", "اصفهان", "تبریز", "ایرانسل", "همراه", "مخابرات", "شاتل", "ir") -> "ir"
            containsMatch(text, "ایسلند", "is") -> "is"
            containsMatch(text, "ایتالیا", "رم", "میلان", "it") -> "it"
            containsMatch(text, "جامائیکا", "jm") -> "jm"
            containsMatch(text, "اردن", "jo") -> "jo"
            containsMatch(text, "ژاپن", "توکیو", "اوساکا", "jp") -> "jp"
            containsMatch(text, "کنیا", "ke") -> "ke"
            containsMatch(text, "قرقیزستان", "kg") -> "kg"
            containsMatch(text, "کامبوج", "kh") -> "kh"
            containsMatch(text, "کره شمالی", "kp") -> "kp"
            containsMatch(text, "کره جنوبی", "سئول", "kr") -> "kr"
            containsMatch(text, "کویت", "kw") -> "kw"
            containsMatch(text, "قزاقستان", "kz") -> "kz"
            containsMatch(text, "لائوس", "la") -> "la"
            containsMatch(text, "لبنان", "بیروت", "lb") -> "lb"
            containsMatch(text, "لیختن اشتاین", "لیختن", "li") -> "li"
            containsMatch(text, "سریلانکا", "lk") -> "lk"
            containsMatch(text, "لیبریا", "lr") -> "lr"
            containsMatch(text, "لیتوانی", "lt") -> "lt"
            containsMatch(text, "لوکزامبورگ", "lu") -> "lu"
            containsMatch(text, "لتونی", "ریگا", "lv") -> "lv"
            containsMatch(text, "لیبی", "ly") -> "ly"
            containsMatch(text, "مراکش", "ma") -> "ma"
            containsMatch(text, "موناکو", "mc") -> "mc"
            containsMatch(text, "مولداوی", "md") -> "md"
            containsMatch(text, "مونته نگرو", "مونته", "me") -> "me"
            containsMatch(text, "ماداگاسکار", "mg") -> "mg"
            containsMatch(text, "مقدونیه", "mk") -> "mk"
            containsMatch(text, "مالی", "ml") -> "ml"
            containsMatch(text, "میانمار", "mm") -> "mm"
            containsMatch(text, "مغولستان", "mn") -> "mn"
            containsMatch(text, "ماکائو", "mo") -> "mo"
            containsMatch(text, "موریتانی", "mr") -> "mr"
            containsMatch(text, "مالت", "mt") -> "mt"
            containsMatch(text, "موریس", "mu") -> "mu"
            containsMatch(text, "مالدیو", "mv") -> "mv"
            containsMatch(text, "مالاوی", "mw") -> "mw"
            containsMatch(text, "مکزیک", "mx") -> "mx"
            containsMatch(text, "مالزی", "کوالالامپور", "my") -> "my"
            containsMatch(text, "موزامبیک", "mz") -> "mz"
            containsMatch(text, "نامیبیا", "na") -> "na"
            containsMatch(text, "نیجر", "ne") -> "ne"
            containsMatch(text, "نیجریه", "ng") -> "ng"
            containsMatch(text, "نیکاراگوئه", "ni") -> "ni"
            containsMatch(text, "هلند", "آمستردام", "امستردام", "nl") -> "nl"
            containsMatch(text, "نروژ", "اسلو", "no") -> "no"
            containsMatch(text, "نپال", "np") -> "np"
            containsMatch(text, "نائورو", "nr") -> "nr"
            containsMatch(text, "نیوزلند", "nz") -> "nz"
            containsMatch(text, "عمان", "مسقط", "om") -> "om"
            containsMatch(text, "پاناما", "pa") -> "pa"
            containsMatch(text, "پرو", "pe") -> "pe"
            containsMatch(text, "فیلیپین", "ph") -> "ph"
            containsMatch(text, "پاکستان", "کراچی", "pk") -> "pk"
            containsMatch(text, "لهستان", "ورشو", "pl") -> "pl"
            containsMatch(text, "پورتوریکو", "pr") -> "pr"
            containsMatch(text, "فلسطین", "غزه", "ps") -> "ps"
            containsMatch(text, "پرتغال", "لیسبون", "pt") -> "pt"
            containsMatch(text, "پالائو", "pw") -> "pw"
            containsMatch(text, "پاراگوئه", "py") -> "py"
            containsMatch(text, "قطر", "دوحه", "qa") -> "qa"
            containsMatch(text, "رومانی", "بخارست", "ro") -> "ro"
            containsMatch(text, "صربستان", "بلگراد", "rs") -> "rs"
            containsMatch(text, "روسیه", "مسکو", "ru") -> "ru"
            containsMatch(text, "رواندا", "rw") -> "rw"
            containsMatch(text, "عربستان", "ریاض", "جده", "sa") -> "sa"
            containsMatch(text, "سودان", "sd") -> "sd"
            containsMatch(text, "سوئد", "استکهلم", "se") -> "se"
            containsMatch(text, "سنگاپور", "sg") -> "sg"
            containsMatch(text, "اسلوونی", "si") -> "si"
            containsMatch(text, "اسلواکی", "sk") -> "sk"
            containsMatch(text, "سنگال", "sn") -> "sn"
            containsMatch(text, "سومالی", "so") -> "so"
            containsMatch(text, "سوریه", "دمشق", "sy") -> "sy"
            containsMatch(text, "چاد", "td") -> "td"
            containsMatch(text, "توگو", "tg") -> "tg"
            containsMatch(text, "تایلند", "بانکوک", "th") -> "th"
            containsMatch(text, "تاجیکستان", "tj") -> "tj"
            containsMatch(text, "ترکمنستان", "tm") -> "tm"
            containsMatch(text, "تونس", "tn") -> "tn"
            containsMatch(text, "ترکیه", "استانبول", "آنکارا", "انکارا", "tr") -> "tr"
            containsMatch(text, "تایوان", "تایپه", "tw") -> "tw"
            containsMatch(text, "تانزانیا", "tz") -> "tz"
            containsMatch(text, "اوکراین", "کیف", "ua") -> "ua"
            containsMatch(text, "اوگاندا", "ug") -> "ug"
            containsMatch(text, "آمریکا", "امریکا", "ایالات متحده", "نیویورک", "کالیفرنیا", "us", "usa") -> "us"
            containsMatch(text, "اروگوئه", "uy") -> "uy"
            containsMatch(text, "ازبکستان", "تاشکند", "uz") -> "uz"
            containsMatch(text, "واتیکان", "va") -> "va"
            containsMatch(text, "ونزوئلا", "ve") -> "ve"
            containsMatch(text, "ویتنام", "هانوی", "vn") -> "vn"
            containsMatch(text, "یمن", "ye") -> "ye"
            containsMatch(text, "آفریقای جنوبی", "za") -> "za"
            containsMatch(text, "زامبیا", "zm") -> "zm"
            containsMatch(text, "زیمبابوه", "zw") -> "zw"
            containsMatch(text, "ad") -> "ad"
            containsMatch(text, "ag") -> "ag"
            containsMatch(text, "ai") -> "ai"
            containsMatch(text, "aq") -> "aq"
            containsMatch(text, "as") -> "as"
            containsMatch(text, "aw") -> "aw"
            containsMatch(text, "ax") -> "ax"
            containsMatch(text, "bb") -> "bb"
            containsMatch(text, "bf") -> "bf"
            containsMatch(text, "bi") -> "bi"
            containsMatch(text, "bj") -> "bj"
            containsMatch(text, "bl") -> "bl"
            containsMatch(text, "bm") -> "bm"
            containsMatch(text, "bq") -> "bq"
            containsMatch(text, "bv") -> "bv"
            containsMatch(text, "bw") -> "bw"
            containsMatch(text, "cc") -> "cc"
            containsMatch(text, "cf") -> "cf"
            containsMatch(text, "cg") -> "cg"
            containsMatch(text, "ci") -> "ci"
            containsMatch(text, "ck") -> "ck"
            containsMatch(text, "cv") -> "cv"
            containsMatch(text, "cw") -> "cw"
            containsMatch(text, "cx") -> "cx"
            containsMatch(text, "dj") -> "dj"
            containsMatch(text, "dm") -> "dm"
            containsMatch(text, "eh") -> "eh"
            containsMatch(text, "fk") -> "fk"
            containsMatch(text, "fm") -> "fm"
            containsMatch(text, "fo") -> "fo"
            containsMatch(text, "gd") -> "gd"
            containsMatch(text, "gf") -> "gf"
            containsMatch(text, "gg") -> "gg"
            containsMatch(text, "gp") -> "gp"
            containsMatch(text, "gq") -> "gq"
            containsMatch(text, "gs") -> "gs"
            containsMatch(text, "gw") -> "gw"
            containsMatch(text, "gy") -> "gy"
            containsMatch(text, "hm") -> "hm"
            containsMatch(text, "im") -> "im"
            containsMatch(text, "io") -> "io"
            containsMatch(text, "je") -> "je"
            containsMatch(text, "ki") -> "ki"
            containsMatch(text, "km") -> "km"
            containsMatch(text, "kn") -> "kn"
            containsMatch(text, "ky") -> "ky"
            containsMatch(text, "lc") -> "lc"
            containsMatch(text, "mf") -> "mf"
            containsMatch(text, "mh") -> "mh"
            containsMatch(text, "mp") -> "mp"
            containsMatch(text, "mq") -> "mq"
            containsMatch(text, "ms") -> "ms"
            containsMatch(text, "nc") -> "nc"
            containsMatch(text, "nf") -> "nf"
            containsMatch(text, "nu") -> "nu"
            containsMatch(text, "pf") -> "pf"
            containsMatch(text, "pg") -> "pg"
            containsMatch(text, "pm") -> "pm"
            containsMatch(text, "pn") -> "pn"
            containsMatch(text, "re") -> "re"
            containsMatch(text, "sb") -> "sb"
            containsMatch(text, "sc") -> "sc"
            containsMatch(text, "sh") -> "sh"
            containsMatch(text, "sj") -> "sj"
            containsMatch(text, "sl") -> "sl"
            containsMatch(text, "sm") -> "sm"
            containsMatch(text, "sr") -> "sr"
            containsMatch(text, "ss") -> "ss"
            containsMatch(text, "st") -> "st"
            containsMatch(text, "sv") -> "sv"
            containsMatch(text, "sx") -> "sx"
            containsMatch(text, "sz") -> "sz"
            containsMatch(text, "tc") -> "tc"
            containsMatch(text, "tf") -> "tf"
            containsMatch(text, "tk") -> "tk"
            containsMatch(text, "tl") -> "tl"
            containsMatch(text, "to") -> "to"
            containsMatch(text, "tt") -> "tt"
            containsMatch(text, "tv") -> "tv"
            containsMatch(text, "um") -> "um"
            containsMatch(text, "vc") -> "vc"
            containsMatch(text, "vg") -> "vg"
            containsMatch(text, "vi") -> "vi"
            containsMatch(text, "vu") -> "vu"
            containsMatch(text, "wf") -> "wf"
            containsMatch(text, "ws") -> "ws"
            containsMatch(text, "xk") -> "xk"
            containsMatch(text, "yt") -> "yt"
            else -> null
        }
    }

    private fun containsExact(text: String, vararg keywords: String): Boolean {
        for (keyword in keywords) {
            if (text.contains(keyword)) return true
        }
        return false
    }

    private fun containsMatch(text: String, vararg keywords: String): Boolean {
        for (keyword in keywords) {
            if (keyword.length <= 3) {
                // مرزبندی برای کدهای کوتاه تا به عنوان بخشی از یک کلمه دیگر شمرده نشوند
                val pattern = Pattern.compile("(?<![a-z0-9])${Pattern.quote(keyword)}(?![a-z0-9])")
                if (pattern.matcher(text).find()) return true
            } else {
                if (text.contains(keyword)) return true
            }
        }
        return false
    }
}